[workspace]
resolver = "2"
members = [
  "crates/podbay-core",
  "crates/podbay-wire",
  "crates/podbay-store",
  "crates/podbay-host",
  "crates/podbay-pod",
  "crates/podbay-macos-sys",
  "crates/podbay-win32",
  "crates/podbay-client",
  "crates/podbay-server",
  "crates/podbay-cli",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "UPL-1.0"
