[package]
name = "podbay-host"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
ed25519-compact = { version = "2", default-features = false }
getrandom = "0.4"
podbay-core = { path = "../podbay-core" }
podbay-store = { path = "../podbay-store" }
podbay-wire = { path = "../podbay-wire" }
sha2 = "0.11"

[dev-dependencies]
rusqlite = { version = "0.40.2", features = ["bundled"] }

[target.'cfg(target_os = "linux")'.dependencies]
libc = "0.2"
rustix = { version = "1", features = ["fs"] }

[lib]
path = "src/lib.rs"
