[package]
name = "podbay-launch-linux"
version.workspace = true
edition.workspace = true
license.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
podbay-core = { path = "../podbay-core" }
podbay-host = { path = "../podbay-host" }
podbay-store = { path = "../podbay-store" }
podbay-wire = { path = "../podbay-wire" }
podbay-pod = { path = "../podbay-pod" }
sha2 = "0.11"
